plugins { id 'com.android.application' }

android {
    buildFeatures { buildConfig true }
    namespace 'com.arichat.ai'
    compileSdk 35
    defaultConfig {
        applicationId 'com.arichat.ai'
        minSdk 23
        targetSdk 35
        versionCode 20
        versionName '1.0.20'
        }
}