plugins { id 'com.android.application' }

def buildNumber = System.getenv("GITHUB_RUN_NUMBER") ?: "23"
def appVersionCode = buildNumber.toInteger()

android {
    buildFeatures { buildConfig true }
    namespace 'com.arichat.ai'
    compileSdk 35
    defaultConfig {
        applicationId 'com.arichat.ai'
        minSdk 23
        targetSdk 35
        versionCode appVersionCode
        versionName "1.0.${buildNumber}"
    }
}